### ISSUE TITLE
WD creation hangs on multithreading

### ISSUE THREAD

**Issue by greyxray** [KIT-CMS/friend-tree-producer#8]
[this line](https://github.com/KIT-CMS/friend-tree-producer/blob/82552accb808a7da6ed55b78bffc6870e8218b3d/scripts/job_management.py#L133) hangs when creating wd with multiple threads taking as input `/store/...` locations (eg when accessing files via, for example, root://). Need to fix it properly - in meanwhile calls with `--cores 1` incorporates [current hotfix](https://github.com/KIT-CMS/friend-tree-producer/commit/82552accb808a7da6ed55b78bffc6870e8218b3d#diff-e0fd3a08aa951cdd374b7f823be64d2dR167)

testing command:
```
python HiggsAnalysis/friend-tree-producer/scripts/job_management.py  \
            --executable SVFit \
            --input_ntuples_directory /store/user/mburkart/mergedArtusOutputs/2019_19_11_ttmc \
            --batch_cluster etp7  \
            --command submit \
            --events_per_job 20000 \
            --walltime 3600 \
            --custom_workdir_path /ceph/ohlushch/MSSM_Legacy_mva_v0/SVfit/delme_please \
            --mode xrootd --cores 2 --debug
```

**Comment by mova** [comment]
I assume this is fixed now, can I close it?
